"""Added some fields to usre type table

Revision ID: 069b4138ae1c
Revises: 681443760e3e
Create Date: 2025-09-27 21:25:34.568522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069b4138ae1c'
down_revision = '681443760e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_type', sa.String(), nullable=True))

    with op.batch_alter_table('user_extra_fields', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_extra_fields_user_type_fkey'), type_='foreignkey')
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_extra_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('user_extra_fields_user_type_fkey'), 'user_type', ['user_type'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('blood_type')

    # ### end Alembic commands ###
