"""Added is active to usre type table

Revision ID: 681443760e3e
Revises: 44c7e0ad1123
Create Date: 2025-09-27 14:21:37.407713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681443760e3e'
down_revision = '44c7e0ad1123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
