"""Added orders table

Revision ID: b0a568243893
Revises: 2665b7c63b1a
Create Date: 2025-09-28 20:12:05.262921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a568243893'
down_revision = '2665b7c63b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taken_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('taken_by_phone_no', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('taken_by_phone_no')
        batch_op.drop_column('taken_by')

    # ### end Alembic commands ###
