"""Added price to medicine table

Revision ID: f27501ac7293
Revises: 57c9c974b455
Create Date: 2025-09-28 19:07:02.355622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27501ac7293'
down_revision = '57c9c974b455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_stock', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
